//! Centralized product identity. Change these constants to rename the app.
pub const APP_NAME: &str = "server-tui";
pub const APP_VERSION: &str = env!("CARGO_PKG_VERSION");
pub const BINARY_NAME: &str = "server-tui";
pub const CONFIG_DIR_NAME: &str = "server-tui";

pub mod actions;
pub mod app;
pub mod cli;
pub mod config;
pub mod diagnostics;
pub mod doctor;
pub mod error;
pub mod fsutil;
pub mod glossary;
pub mod keymap;
pub mod model;
pub mod persist;
pub mod preview;
pub mod profile;
pub mod providers;
pub mod runtime;
pub mod sanitize;
pub mod settings;
pub mod setup;
pub mod status;
pub mod support;
pub mod terminal;
pub mod theme;
pub mod ui;
pub mod viewport;
