//! Startup console unit generator (library — tests never modify the host).

use std::path::{Path, PathBuf};

use crate::error::AppError;
use crate::BINARY_NAME;

pub const DEFAULT_TTY: &str = "tty2";
pub const UNIT_NAME: &str = "server-tui-console.service";

#[derive(Debug, Clone)]
pub struct ConsoleInstallSpec {
    pub tty: String,
    pub user: String,
    pub wallboard: bool,
    pub read_only: bool,
    pub exec_start: PathBuf,
}

impl Default for ConsoleInstallSpec {
    fn default() -> Self {
        Self {
            tty: DEFAULT_TTY.into(),
            user: whoami_fallback(),
            wallboard: true,
            read_only: true,
            exec_start: PathBuf::from(format!("/usr/local/bin/{BINARY_NAME}")),
        }
    }
}

fn whoami_fallback() -> String {
    std::env::var("USER").unwrap_or_else(|_| "nobody".into())
}

/// Generate a systemd unit body. Does not write to disk.
pub fn generate_unit(spec: &ConsoleInstallSpec) -> Result<String, AppError> {
    validate_tty(&spec.tty)?;
    validate_user(&spec.user)?;
    if !spec.exec_start.is_absolute() {
        return Err(AppError::Internal(
            "ExecStart must be an absolute path".into(),
        ));
    }
    let mut args = vec![spec.exec_start.display().to_string()];
    if spec.wallboard {
        args.push("--wallboard".into());
    }
    if spec.read_only {
        args.push("--read-only".into());
    }
    let exec = args.join(" ");
    let tty_path = format!("/dev/{}", spec.tty);
    let getty_conflict = format!("getty@{}.service", spec.tty);
    Ok(format!(
        "# Generated by {BINARY_NAME} setup console — do not hand-edit casually.\n\
[Unit]\n\
Description=server-tui console on {tty}\n\
Conflicts={getty_conflict}\n\
After=systemd-user-sessions.service\n\
\n\
[Service]\n\
Type=simple\n\
User={user}\n\
TTYPath={tty_path}\n\
StandardInput=tty\n\
StandardOutput=tty\n\
StandardError=journal\n\
ExecStart={exec}\n\
Restart=on-failure\n\
\n\
[Install]\n\
WantedBy=multi-user.target\n",
        BINARY_NAME = BINARY_NAME,
        tty = spec.tty,
        getty_conflict = getty_conflict,
        user = spec.user,
        tty_path = tty_path,
        exec = exec,
    ))
}

pub fn validate_tty(tty: &str) -> Result<(), AppError> {
    if tty.is_empty()
        || tty.contains('/')
        || tty.contains('\0')
        || !tty.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
    {
        return Err(AppError::Internal(format!("invalid tty: {tty}")));
    }
    Ok(())
}

pub fn validate_user(user: &str) -> Result<(), AppError> {
    if user.is_empty() || user == "root" {
        return Err(AppError::Internal(
            "console unit must use a non-root User=".into(),
        ));
    }
    if !user
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        return Err(AppError::Internal(format!("invalid user: {user}")));
    }
    Ok(())
}

/// Status text for CLI (does not require root). Describes expected conflict.
pub fn status_text(spec: &ConsoleInstallSpec) -> String {
    format!(
        "unit: {UNIT_NAME}\ntty: {}\nuser: {}\nwallboard: {}\nread_only: {}\nconflicts: getty@{}.service\nexec: {}\nnote: install/remove require admin confirmation and are not performed by tests/smoke.",
        spec.tty,
        spec.user,
        spec.wallboard,
        spec.read_only,
        spec.tty,
        spec.exec_start.display()
    )
}

/// Paths that would be written on install (for confirmation messaging only).
pub fn install_paths(tty: &str) -> (PathBuf, PathBuf) {
    let unit = PathBuf::from("/etc/systemd/system").join(UNIT_NAME);
    let getty = PathBuf::from(format!("/etc/systemd/system/getty@{tty}.service"));
    (unit, getty)
}

pub fn unit_basename() -> &'static str {
    UNIT_NAME
}

/// Filesystem operations for install/remove. Tests use `DryRunFs`.
pub trait ConsoleFsOps {
    fn write_unit(&mut self, path: &Path, body: &str) -> Result<(), AppError>;
    fn remove_unit(&mut self, path: &Path) -> Result<(), AppError>;
    fn path_exists(&self, path: &Path) -> bool;
}

#[derive(Default)]
pub struct DryRunFs {
    pub writes: Vec<(PathBuf, String)>,
    pub removes: Vec<PathBuf>,
}

impl ConsoleFsOps for DryRunFs {
    fn write_unit(&mut self, path: &Path, body: &str) -> Result<(), AppError> {
        self.writes.push((path.to_path_buf(), body.to_string()));
        Ok(())
    }

    fn remove_unit(&mut self, path: &Path) -> Result<(), AppError> {
        self.removes.push(path.to_path_buf());
        Ok(())
    }

    fn path_exists(&self, path: &Path) -> bool {
        self.writes.iter().any(|(p, _)| p == path) && !self.removes.iter().any(|p| p == path)
    }
}

/// Real FS writer — never called from tests/smoke.
pub struct RealFs;

impl ConsoleFsOps for RealFs {
    fn write_unit(&mut self, path: &Path, body: &str) -> Result<(), AppError> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| AppError::Internal(e.to_string()))?;
        }
        let tmp = path.with_extension("service.tmp");
        std::fs::write(&tmp, body).map_err(|e| AppError::Internal(e.to_string()))?;
        std::fs::rename(&tmp, path).map_err(|e| AppError::Internal(e.to_string()))?;
        Ok(())
    }

    fn remove_unit(&mut self, path: &Path) -> Result<(), AppError> {
        if path.exists() {
            std::fs::remove_file(path).map_err(|e| AppError::Internal(e.to_string()))?;
        }
        Ok(())
    }

    fn path_exists(&self, path: &Path) -> bool {
        path.exists()
    }
}

/// Install unit body via FsOps. Does not run systemctl enable (caller responsibility).
pub fn install_console_unit(
    fs: &mut dyn ConsoleFsOps,
    spec: &ConsoleInstallSpec,
) -> Result<PathBuf, AppError> {
    let body = generate_unit(spec)?;
    let (unit, _) = install_paths(&spec.tty);
    // Refuse installing as root User already in generate_unit.
    fs.write_unit(&unit, &body)?;
    Ok(unit)
}

/// Remove generated unit file via FsOps. Does not restore getty automatically
/// (document that getty@ttyN should be re-enabled by the operator).
pub fn remove_console_unit(fs: &mut dyn ConsoleFsOps, tty: &str) -> Result<PathBuf, AppError> {
    validate_tty(tty)?;
    let (unit, _) = install_paths(tty);
    fs.remove_unit(&unit)?;
    Ok(unit)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_unit_with_conflicts_and_flags() {
        let spec = ConsoleInstallSpec {
            tty: "tty2".into(),
            user: "admin".into(),
            wallboard: true,
            read_only: true,
            exec_start: PathBuf::from("/usr/local/bin/server-tui"),
        };
        let body = generate_unit(&spec).expect("unit");
        assert!(body.contains("Conflicts=getty@tty2.service"));
        assert!(body.contains("User=admin"));
        assert!(body.contains("--wallboard"));
        assert!(body.contains("--read-only"));
        assert!(body.contains("TTYPath=/dev/tty2"));
        assert!(!body.contains("User=root"));
    }

    #[test]
    fn rejects_root_and_relative_exec() {
        let spec = ConsoleInstallSpec {
            user: "root".into(),
            ..ConsoleInstallSpec::default()
        };
        assert!(generate_unit(&spec).is_err());
        let spec = ConsoleInstallSpec {
            user: "alice".into(),
            exec_start: PathBuf::from("server-tui"),
            ..ConsoleInstallSpec::default()
        };
        assert!(generate_unit(&spec).is_err());
    }

    #[test]
    fn dry_run_install_remove() {
        let spec = ConsoleInstallSpec {
            tty: "tty3".into(),
            user: "admin".into(),
            wallboard: true,
            read_only: true,
            exec_start: PathBuf::from("/usr/local/bin/server-tui"),
        };
        let mut fs = DryRunFs::default();
        let path = install_console_unit(&mut fs, &spec).expect("install");
        assert_eq!(fs.writes.len(), 1);
        assert!(fs.writes[0].1.contains("Conflicts=getty@tty3.service"));
        remove_console_unit(&mut fs, "tty3").expect("remove");
        assert_eq!(fs.removes[0], path);
    }

    #[test]
    fn validates_tty() {
        assert!(validate_tty("tty2").is_ok());
        assert!(validate_tty("../tty").is_err());
    }
}
